### ISSUE TITLE
connection between behavior process and phenotype

### ISSUE THREAD

**Issue by cmungall** [obo-behavior/behavior-ontology#36] opened 2016-02-13 02:37 UTC
is the intention that these are disjoint?

That might seem a natural interpretation given

```
 NBO:0000243 ! behavioral phenotype [DEF: ""An observable characteristic of the behavior of an organism." [NBO:RH]"]
 NBO:0000313 ! behavior process [DEF: ""The action, reaction, or performance of an organism in response to external or internal stimuli." [GO:GO:0007610]"]
```

and an interpretation of 'characteristic' as being something attribute-like.

It seems the hierarchies are largely disjoint, with the exception of: NBO:0000096 ! agoraphobia behavior

![d](https://cloud.githubusercontent.com/assets/50745/13025253/973c6420-d1b7-11e5-81fe-6f553f63f727.png)

it seems there shoukd either be zero or a lot more crossings

**Comment by pmidford** [comment] 2016-02-13 02:48
Our recent discussions with Robert and George have lead (at least me) to
conclude that these are separate hierarchies: processes and dispositions
(including phenotypes and functions).

I agree your diagram depicts an error, my vote is that the problem is
right at the bottom.  It should be something like:  agoraphobia behavior
realizes agoraphobia (behavior) phenotype which is_a phobia.

**Comment by aclark-binghamton-edu** [comment] 2016-07-10 20:55
And as I understand it, the concept of a behavioral phenotype in NBO is not drawn, as one would expect, from evolution-based biology, but is a Gene Ontology concept. GO constrains the ontology by requiring terms at lower levels that then must find a parent or grand-parent, no matter how cumbersome.

**Comment by cmungall** [comment] 2016-07-10 21:06
Hi Ann,

I'm not sure I understand your comment. GO doesn't have (abnormal) phenotypes.

> GO constrains the ontology by requiring terms at lower levels that then must find a parent or grand-parent, no matter how cumbersome.

I'm not sure I understand this, but I don't think GO does anything different from any other ontology here

**Comment by cmungall** [comment] 2016-07-10 21:07
@pmidford your solution sounds like it's on the right track. I'm not sure we want to commit to BFO dispositions, quality would be more conventional, or hedge up to the level of dependent continuant

**Comment by pmidford** [comment] 2016-07-10 22:32
I think I've been following Barry Smith on this (re: process
phenotypes).  It also brings a certain harmony, as functions are
explicitly stated to be dispositions in the Arp et al. book, but I won't
object to dependent continuant.

Is the issue of process phenotypes something we should take (back) to
OBO-discuss?

**Comment by DitchingIt** [comment] 2023-01-14 05:25
I'm closing this issue because that was the intention in 2017 and so we can focus further discussion at #120

**Closed** 2023-02-21 12:46 UTC
